spring:
  datasource:
    url: jdbc:h2:mem:sfr3db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080
